# Report for 2D Project Physical World and Digital World

Cohort: # enter your cohort

Team No.: # Enter your team number

Members:
* Student 1 Name (Student ID)
* Student 2 Name (Student ID)


# Introduction

Write your introduction here. Describe the problem you want to solve and a brief of your approach and summary of your result.


# Description of Data from Experiment

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv

## Data Collection

Describe how you collect your data and the reasoning behind such approach.



## Data Preparation

Describe how you prepare your data. Include any codes you have here.

In [4]:
def text_to_nested_list(file_address_input):
    txt_file_open = open(file_address_input, 'r')
    file_readlines = txt_file_open.readlines()

    data_frame_collective = []
    for i in file_readlines:
        #print(i)
        i_list = i.split()
        frame_name = int(i_list[0])
        i_list = i_list[1:]
        time_list = []
        temp_list = []
        for j in range(1,int(len(i_list)/2)):
            time_list.append(round(float(i_list[j*2-2]),0))
            temp_list.append(float(i_list[j*2-1]))
        #print("time_list: {0}, temp_list: {1} ".format(time_list, temp_list))
        data_frame_collective.append([frame_name,time_list,temp_list])
    return data_frame_collective

def function_for_jerry(address_input):
    address = address_input
    data_frame_collective = text_to_nested_list(address)

    output_matrix = np.empty([0,16])

    for i in data_frame_collective:
        data_row = i[2][:15]
        data_row.insert(0,i[0])
        data_row = np.array([data_row])
        data_row.reshape(-1,1)
        output_matrix = np.vstack((output_matrix, data_row[:1]))

    return output_matrix

address = r'C:\Users\Apple\Desktop\data_real_3.txt'

## Data Format

Describe your data and its features. Include any codes or visualization of data.

In [7]:
# Take the temperature of the sensor at 25 second and its corrsponding water bath temperature.
# Combine the data into a n*2 matrix
mat = function_for_jerry(address)
mat_0 = list(mat[:, 0, np.newaxis])
mat_1 = list(mat[:, -1, np.newaxis])
raw_matrix = list(np.concatenate((mat_0, mat_1), axis = 1))
print(len(raw_matrix))

#raw_matrix has 140 instances, thus 140 rows, and 10 different water bath temperature. Find the average temperature at 25 second
matrix = []
vec_b = []
temp = 10
while temp <= 60:
    average = 0
    count = 0
    for i in raw_matrix:
        if i[0] == temp:
            average += i[-1]
            count += 1
    if count != 0:    
        average /= count
        matrix.append([1, average])
        vec_b.append([temp])
    temp += 5

for i in range(len(matrix)):
    matrix[i] = list(matrix[i])

matrix = np.array(matrix)
vec_b = np.array(vec_b)
print(vec_b)
print(matrix)

140
[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]
 [50]
 [55]
 [60]]
[[ 1.         13.26415385]
 [ 1.         16.8525    ]
 [ 1.         20.51892308]
 [ 1.         24.6248    ]
 [ 1.         28.03823077]
 [ 1.         31.83325   ]
 [ 1.         35.67675   ]
 [ 1.         39.61441667]
 [ 1.         44.26016667]
 [ 1.         48.1925    ]
 [ 1.         51.69775   ]]


# Training Model

Describe how you train your model. Include any code and output

In [8]:
def find_solution(matrix, array_d):
    matrix_inv = inv(np.matmul(matrix.transpose(), matrix))
    return np.matmul(np.matmul(matrix_inv, matrix.transpose()), array_d)

# Find the solution to the linear regression
solution = find_solution(matrix, vec_b)
print(solution)

[[-6.55107321]
 [ 1.28904693]]


# Verification and Accuracy

Describe how you check the accuracy of your model and its result. State any analysis you have and the steps you have taken to improve its accuracy.

In [10]:
def find_error(actual, predicted):
    act_len = len(actual)
    pre_len = len(predicted)
    if not act_len == pre_len:
        return "inconsistent array length"
    
    err = []
    for i in range(act_len):
        err.append(abs(actual[i][0] - predicted[i][0]))
    return err

predicted = np.matmul(matrix, solution)
find_error(vec_b, predicted)

[0.5470435726926208,
 0.17259016308449837,
 0.10121842859276597,
 0.19144961062377774,
 0.4084779383863051,
 0.5165200528459195,
 0.5620681806051095,
 0.4862310558680534,
 0.5023587152943563,
 0.5713209230758594,
 0.08975267152705158]

# Testing Using Instructor's Data

Instruction:

* Store your trained model into a pickle object which can be loaded. 
* Read an excel file with the following format:
```
time (s)	reading
0.00	    25.812
0.90	    28.562
1.79	    31.875
2.68	    35.062
3.55	    37.937
4.43	    40.687
5.30	    43.25
```
where the first column indicates the time in seconds and the second column indicates the sensor reading in Celsius. 
* The number of rows in the instructors' data can be of any number. If your code has a minimum number of rows, your code must be able to handle and exit safely when the data provided is less than the required minimum.
* Write a code to prepare the data for prediction.
* Write a code to predict the final temperature.



In [6]:
# write a code to load your trained model from a pickle object
import pickle
filename = '' # enter your pickle file name containing the model
with open(filename,'rb') as f:
    model = pickle.load(f)


FileNotFoundError: [Errno 2] No such file or directory: ''

In [ ]:
# write a code to read an excel file
import pandas as pd
num_test = 9
filename = 'temp_' 
filekey = [] # instructors will key in this
dataframe = {} # this is to store the data for different temperature, the keys are in filekey
for idx in range(num_test):
    dataframe[filekey[idx]] = pd.read_excel(filename+filekey[idx]+'.xlsx')


In [ ]:
# write a code to prepare the data for predicting
def preprocess(df):
    # use this function to extract the features from the data frame
    
    pass

data_test = {}
for key in filekey:
    data_test[key]=preprocess(dataframe[key])

In [ ]:
# write a code to predict the final temperature
# store the predicted temperature in a variable called "predicted"
# predicted is a dictionary where the keys are listed in filekey

predicted = {}
for key in filekey:
    predicted[key]=model.predict(data_test[key])

In [ ]:
# checking accuracy

# first instructor will load the actual temp from a pickle object
import pickle
error_d = {}
accuracy_percent_d = {}

for test in range(num_test):
    filename = 'data_'+filekey[test]+'.pickle'
    with open(filename,'rb') as f:
        final_temp, worst_temp = pickle.load(f)

    # then calculate the error
    error_final = abs(final_temp-predicted[filekey[test]])
    accuracy_final_percent = 100-error_final/final_temp*100
    error_worst = abs(worst_temp-predicted[filekey[test]])
    accuracy_worst_percent = 100-error_worst/worst_temp*100
    
    error_d[filekey[test]] = (error_final, error_worst)
    accuracy_percent_d[filekey[test]] = (accuracy_final_percent, accuracy_worst_percent)

    # displaying the error
    print('===================================')
    print('Testing: {}'.format(filekey[test]))
    print('Predicted Temp: {:.2f}'.format(predicted[filekey[test]]))
    print('Final Sensor Temp: {:.2f}, Alcohol Temp:{:.2f}'.format(final_temp, worst_temp))
    print('Error w.r.t Final Sensor Temp: {:.2f} deg, {:.2f}% accuracy'.format(error_final, accuracy_final_percent))
    print('Error w.r.t Alcohol Temp: {:.2f} deg, {:.2f}% accuracy'.format(error_worst, accuracy_worst_percent))
    
avg_final = sum([ final for final, worst in accuracy_percent_d.values()])/len(error_d.values())
avg_worst = sum([ worst for final, worst in accuracy_percent_d.values()])/len(error_d.values())
print('==============================')
print('Average accuracy for final sensor temp: {:.2f}'.format(avg_final))
print('AVerage accuracy for alcohol temp: {:.2f}'.format(avg_worst))
